package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Kotest'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("Kotest")
    name = "Kotest"
    url = "git@github.com:jb-assignment/kotest.git"
    branch = "master"
    authMethod = uploadedKey {
        uploadedKey = "id_allegro_open_source"
    }
}))

